import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Image from "next/image";

import nofCanaanLogoTransparent from "/public/temp.svg";

import styles from "./layout.module.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tzimer Nof Canaan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.body}`}>
        <Header />
        {children}
        {/* TODO blue footer */}
        <div className={styles.footer}>
          {/* google maps */}
          <div className={styles.googleMaps}>
            <Image
              width={800}
              height={500}
              src="/map.PNG"
              alt="google maps location"
            />
          </div>

          {/* contact */}
          <div>
            <h3> Contact & Reservation</h3>
            <p>canaani@netvision.net.il</p>
            <p>054 - 4622258</p>
          </div>

          {/* address */}
          <div>
            <h3> Address </h3>
            <p>25 Nahal Ashalim , Kfar Adumim, 90618,</p>
            <p>054 - 4622258</p>
          </div>
        </div>
      </body>
    </html>
  );
}
