import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Image from "next/image";

import nofCanaanLogoTransparent from "/public/temp.svg";

import styles from "./layout.module.css";
import BackgroundSlideshow from "@/components/backgroundSlideshow";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tzimer Nof Canaan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.body}`}>
        #TODO - as background
        {/* <BackgroundSlideshow /> */}
        <Head>
          <title>Royal Palace Hotel and Resort</title>
        </Head>
        <header className={styles.header}>
          <button className={styles.menuButton}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth={1.5}
              stroke="currentColor"
              className="w-6 h-6"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M3.75 9h16.5m-16.5 6.75h16.5"
              />
            </svg>
            MENU
          </button>
          <div className={styles.logoContainer}>
            <Image
              src={nofCanaanLogoTransparent}
              alt="Nof Canaan Logo"
              width={150}
              height={150}
            />
          </div>
          <button className={styles.menuButton}>RESERVE NOW</button>
        </header>
        {children}
        {/* TODO blue footer */}
        <div className={styles.footer}>
          {/* google maps */}
          <div className={styles.googleMaps}>
            <img src="map.PNG" alt="google maps location" />
          </div>

          {/* contact */}
          <div>
            <h3> Contact & Reservation</h3>
            <p>canaani@netvision.net.il</p>
            <p>054 - 4622258</p>
          </div>

          {/* address */}
          <div>
            <h3> Address </h3>
            <p>25 Nahal Ashalim , Kfar Adumim, 90618,</p>
            <p>054 - 4622258</p>
          </div>
        </div>
      </body>
    </html>
  );
}
